# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_choices', models.CharField(choices=[('1', 'Vegetation'), ('2', 'Trees'), ('3', 'Nature'), ('4', 'Abstract'), ('5', 'IT & Computers'), ('6', 'Animals'), ('7', 'Illustrations'), ('8', 'Arts'), ('9', 'Business'), ('10', 'Industries'), ('11', 'Objects'), ('12', 'Technology'), ('13', 'People'), ('14', 'Travel')], max_length=1)),
            ],
        ),
    ]
