# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.CharField(max_length=30)),
                ('post', models.TextField(default=True)),
                ('category', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='display.Category')),
                ('location', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='display.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
