# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
    ]
