# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_remove_images_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Photos',
        ),
    ]
