# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20180226_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['photo_name']},
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image_description',
            new_name='photo_description',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image_name',
            new_name='photo_name',
        ),
    ]
